version: "3"

services:
  todo_db:
    build: .docker/mysql
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    ports:
      - "33060:3306"
    volumes:
      - ".docker/todo-db:/var/lib/mysql"
      - ".docker/mysql:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=todo
      - MYSQL_DATABASE=todos
      - MYSQL_USER=todo
      - MYSQL_PASSWORD=todo
