GET http://localhost:3001/api/categories
Accept: application/json

###
GET http://localhost:3001/api/categories/1
Accept: application/json

###
POST http://localhost:3001/api/categories
Content-Type: application/json

{
	"label": "This is a comment 1",
	"type": "neutral"
}

###
PUT http://localhost:3001/api/categories/3
Content-Type: application/json

{
	"label": "This is a comment edited",
	"type": "success"
}

###
DELETE http://localhost:3001/api/categories/2
Accept: application/json
