POST http://localhost:3001/api/todo/1/comment
Content-Type: application/json

{
	"comment": "This is a comment",
	"userName": "Janet Johnson",
	"userPhoto": "https://randomuser.me/api/portraits/women/34.jpg"
}

###
DELETE http://localhost:3001/api/todo/2/comment/5
Accept: application/json
