###
GET http://localhost:3001/api/todo
Accept: application/json

###
GET http://localhost:3001/api/todo/1
Accept: application/json

###
POST http://localhost:3001/api/todo
Content-Type: application/json

{
	"title": "TODO Title 1",
	"description": "TODO Description must be a long description. At least 20 caracters long",
	"author": "John Doe",
	"boardIndex": 0,
	"boardRef": "todoColumn"
}

###
PUT http://localhost:3001/api/todo/2
Content-Type: application/json

{
	"boardIndex": 1,
	"boardRef": "todoColumn"
}

###
DELETE http://localhost:3001/api/todo/2
Accept: application/json
